Updates to chapter 7
w3c/wot-architecture pull request #790
Opened 2022-07-04 06:56 UTC by mlagally

editorial fixes, several new assertions

2022-07-06 08:05 UTC, egekorkan requested changes

2022-07-20 12:59 UTC, mlagally commented on index.html
> +      The WoT Profile Specification [[!WOT-PROFILE]] defines a WoT Baseline Profile,
Please suggest concrete text.

2022-07-21 10:50 UTC, mlagally commented on index.html
> +            Forms MAY contain the media type and optional parameters in additional form fields such as a content type
We created issue #810 to continue the discussion.

2022-07-21 10:51 UTC, mlagally commented
Arch call on July 21:
Agree to merge, create issue #810 to align between editors.

2022-07-21 10:51 UTC, merged